
/// <reference lib="webworker" />
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

declare let self: ServiceWorkerGlobalScope & {
  __WB_MANIFEST: any;
};

// 1. Clean up old caches and precache assets generated by Vite
cleanupOutdatedCaches();
precacheAndRoute(self.__WB_MANIFEST);

self.skipWaiting();
clientsClaim();

// --- STRATEGI 1: PETA (CACHE FIRST - AGRESIVE) ---
// Tile peta jarang berubah, kita simpan lama agar hemat kuota & cepat.
registerRoute(
  ({ request }) => request.destination === 'image' && request.url.includes('cartocdn.com'),
  new CacheFirst({
    cacheName: 'map-tiles-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 500, // Simpan maks 500 tile
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Hari
      }),
    ],
  })
);

// --- STRATEGI 2: GOOGLE FONTS & STATIC ASSETS (SWR) ---
// Tampilkan font dari cache dulu biar teks muncul, baru update di background.
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com' || url.origin === 'https://fonts.gstatic.com',
  new StaleWhileRevalidate({
    cacheName: 'google-fonts-stylesheets',
  })
);

// --- STRATEGI 3: API READ / WEATHER (NETWORK FIRST + LIE-FI PROTECTION) ---
// Ini solusi "Lie-Fi". Coba network, tapi jika 3 detik bengong, ambil cache.
registerRoute(
  ({ url }) => url.pathname.includes('/weather') || url.pathname.includes('/api/'), // Sesuaikan jika ada API lain
  new NetworkFirst({
    cacheName: 'api-responses',
    networkTimeoutSeconds: 3, // FALLBACK TIMEOUT: Jika sinyal lemot > 3 detik, pakai cache!
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 60, // Cache valid 1 jam
      }),
    ],
  })
);

// Handler untuk pesan "SKIP_WAITING" dari App.tsx jika ada update versi
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
